In [ ]:
import numpy as np

In [ ]:
# Exercise 1: Create a 1D NumPy array of numbers from 0 to 9
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Exercise 2: Convert 1D array to 2D
arr = np.arange(6)
arr = arr.reshape((2,3))
print(arr)

In [ ]:
# Exercise 3: Print Array Attributes
import numpy as np
my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)

print("The shape oof the array: ",my_array.shape)
print("The number of dimensions is: ",my_array.ndim)
print("The size of each element in bytes is: ",my_array.itemsize)

The shape oof the array:  (4, 2)
The number of dimensions is:  2
The size of each element in bytes is:  2


In [ ]:
# Exercise 4: Create a 3×3 NumPy array of all True
True_arr = np.full((3,3), True)
print(True_arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# Exercise 5: Extract the documentation of NumPy’s arange() function
print(help(np.arange))

In [ ]:
# Exercise 6: Create a 1D array filled with zeros and another filled with ones
zero = np.zeros(6)
ones = np.ones(6)

print("Zeroes", zero)
print("Ones:", ones)

Zeroes [0. 0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1. 1.]


In [ ]:
# Exercise 7: Create a 1D array of 10 evenly spaced values between 5 and 50
array = np.arange(5,51,5)
print(array)
array = np.linspace(5,50, 10)
print(array)

[ 5 10 15 20 25 30 35 40 45 50]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [ ]:
# Exercise 8: Convert a Python list into a NumPy array
py_list = [1,2,3,4,5]
print(np.array(py_list))

[1 2 3 4 5]


In [ ]:
# Exercise 9: Find the memory size of a NumPy array of numbers from 0 to 9
array = np.arange(0,10)
print("Array:", array)
# print("Memory size in bytes: ", array.itemsize) no use nbtyes
print("Memory size in bytes", array.nbytes)

Array: [0 1 2 3 4 5 6 7 8 9]
Memory size in bytes 80


In [ ]:
# Exercise 10: Reverse a 1D NumPy array
array = np.arange(10)
print(array[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [ ]:
# Exercise 11: Create a 3×3 identity matrix
array = np.eye(3).reshape((3,3))
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Exercise 12: Create a 4×4 array and extract its first row and last column
array = np.arange(1,17).reshape((4,4))
print("First Row:", array[0,:] )
print("Last Column", array[:,-1])

First Row: [1 2 3 4]
Last Column [ 4  8 12 16]


In [ ]:
# Exercise 13: Extract Odd Rows and Even Columns
array = np.linspace(3,60,20).reshape((5,4))
#  use slicing, from start from 1 and then skip 1 row and for even start from 0 and skip 1 column
print("New Array with Odd Rows and Even Columns:",array[1::2, ::2])

New Array with Odd Rows and Even Columns: [[15. 21.]
 [39. 45.]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6]


In [ ]:
# Exercise 15: Slice the first two rows and first two columns from a 4×4 array
array = np.arange(1,17).reshape((4,4))
print("First 2 rows and columns", array[0:2, 0:2])

First 2 rows and columns [[1 2]
 [5 6]]


In [ ]:
# Exercise 16: Replace all odd numbers in a NumPy array with -1
array = np.arange(1,11)
array[0::2] = -1
print(array)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [ ]:
# Exercise 17: Get the indices of non-zero elements in an array
array = np.array([1, 0, 2, 0, 3, 0, 4])
# index = array[array == 0] this was for all the zero element
index = array.nonzero()

print("Array: ", array)
print("Indices: ", index)

Array:  [1 0 2 0 3 0 4]
Indices:  (array([0, 2, 4, 6]),)


In [ ]:
# Exercise 18: Find the common items between two arrays
a = np.array([1, 2, 3, 2, 8, 4, 2, 4])
b = np.array([2, 4, 5, 6, 8])

c = np.intersect1d(a,b)
print(c)

[2 4 8]


In [ ]:
# Exercise 19: Perform arithmetic operations on two NumPy arrays element-wise

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Element wise Sum: ", a +b)
print("Element wise multiplication: ",a*b)

Element wise Sum:  [5 7 9]
Element wise multiplication:  [ 4 10 18]


In [ ]:
# Exercise 20: Matrix multiplication
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Dot Product: ", np.dot(a,b))

Dot Product:  32


In [ ]:
# Exercise 21: Compute the mean, median, and standard deviation of a NumPy array
import numpy as np
arr = np.array([10, 20, 30, 100, 200, 300])

print("Mean: ", arr.mean())
print("Median: ",np.median(arr))
print("Standard deviation: ",arr.std())

Mean:  110.0
Median:  65.0
Standard deviation:  107.08252269472673


In [ ]:
# Exercise 22: Remove common items from array
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

# c = np.in1d(a,b) New concept
# mask = np.in1d(a,b) in1d is deprecated.
# using np.isin()
mask = np.isin(a,b)
result = a[~mask] #`~` inverts the mask index :bitwise NOT
print(result)


[1 2 3 4]


In [ ]:
# Exercise 24: Get the positions where elements of array a and b match
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 4, 3, 7, 8])

c = np.where(a == b)
print(c)

(array([0, 2]),)


In [ ]:
# Exercise 25: Extract numbers from an array
arr = np.arange(15)
print(arr[5:11])
print(arr[(arr >=5) &  (arr <= 10)])

[ 5  6  7  8  9 10]
[ 5  6  7  8  9 10]
