In [1]:
import numpy as np

In [ ]:
# Exercise 1: Create a 1D NumPy array of numbers from 0 to 9
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Exercise 2: Convert 1D array to 2D
arr = np.arange(6)
arr = arr.reshape((2,3))
print(arr)

In [ ]:
# Exercise 3: Print Array Attributes
import numpy as np
my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)

print("The shape oof the array: ",my_array.shape)
print("The number of dimensions is: ",my_array.ndim)
print("The size of each element in bytes is: ",my_array.itemsize)

The shape oof the array:  (4, 2)
The number of dimensions is:  2
The size of each element in bytes is:  2


In [ ]:
# Exercise 4: Create a 3×3 NumPy array of all True
True_arr = np.full((3,3), True)
print(True_arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# Exercise 5: Extract the documentation of NumPy’s arange() function
print(help(np.arange))

In [ ]:
# Exercise 6: Create a 1D array filled with zeros and another filled with ones
zero = np.zeros(6)
ones = np.ones(6)

print("Zeroes", zero)
print("Ones:", ones)

Zeroes [0. 0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1. 1.]


In [ ]:
# Exercise 7: Create a 1D array of 10 evenly spaced values between 5 and 50
array = np.arange(5,51,5)
print(array)
array = np.linspace(5,50, 10)
print(array)

[ 5 10 15 20 25 30 35 40 45 50]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [ ]:
# Exercise 8: Convert a Python list into a NumPy array
py_list = [1,2,3,4,5]
print(np.array(py_list))

[1 2 3 4 5]


In [ ]:
# Exercise 9: Find the memory size of a NumPy array of numbers from 0 to 9
array = np.arange(0,10)
print("Array:", array)
# print("Memory size in bytes: ", array.itemsize) no use nbtyes
print("Memory size in bytes", array.nbytes)

Array: [0 1 2 3 4 5 6 7 8 9]
Memory size in bytes 80


In [ ]:
# Exercise 10: Reverse a 1D NumPy array
array = np.arange(10)
print(array[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [ ]:
# Exercise 11: Create a 3×3 identity matrix
array = np.eye(3).reshape((3,3))
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Exercise 12: Create a 4×4 array and extract its first row and last column
array = np.arange(1,17).reshape((4,4))
print("First Row:", array[0,:] )
print("Last Column", array[:,-1])

First Row: [1 2 3 4]
Last Column [ 4  8 12 16]


In [ ]:
# Exercise 13: Extract Odd Rows and Even Columns
array = np.linspace(3,60,20).reshape((5,4))
#  use slicing, from start from 1 and then skip 1 row and for even start from 0 and skip 1 column
print("New Array with Odd Rows and Even Columns:",array[1::2, ::2])

New Array with Odd Rows and Even Columns: [[15. 21.]
 [39. 45.]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6]


In [ ]:
# Exercise 15: Slice the first two rows and first two columns from a 4×4 array
array = np.arange(1,17).reshape((4,4))
print("First 2 rows and columns", array[0:2, 0:2])

First 2 rows and columns [[1 2]
 [5 6]]


In [ ]:
# Exercise 16: Replace all odd numbers in a NumPy array with -1
array = np.arange(1,11)
array[0::2] = -1
print(array)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [ ]:
# Exercise 17: Get the indices of non-zero elements in an array
array = np.array([1, 0, 2, 0, 3, 0, 4])
# index = array[array == 0] this was for all the zero element
index = array.nonzero()

print("Array: ", array)
print("Indices: ", index)

Array:  [1 0 2 0 3 0 4]
Indices:  (array([0, 2, 4, 6]),)


In [ ]:
# Exercise 18: Find the common items between two arrays
a = np.array([1, 2, 3, 2, 8, 4, 2, 4])
b = np.array([2, 4, 5, 6, 8])

c = np.intersect1d(a,b)
print(c)

[2 4 8]


In [ ]:
# Exercise 19: Perform arithmetic operations on two NumPy arrays element-wise

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Element wise Sum: ", a +b)
print("Element wise multiplication: ",a*b)

Element wise Sum:  [5 7 9]
Element wise multiplication:  [ 4 10 18]


In [ ]:
# Exercise 20: Matrix multiplication
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Dot Product: ", np.dot(a,b))

Dot Product:  32


In [ ]:
# Exercise 21: Compute the mean, median, and standard deviation of a NumPy array
import numpy as np
arr = np.array([10, 20, 30, 100, 200, 300])

print("Mean: ", arr.mean())
print("Median: ",np.median(arr))
print("Standard deviation: ",arr.std())

Mean:  110.0
Median:  65.0
Standard deviation:  107.08252269472673


In [ ]:
# Exercise 22: Remove common items from array
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

# c = np.in1d(a,b) New concept
# mask = np.in1d(a,b) in1d is deprecated.
# using np.isin()
mask = np.isin(a,b)
result = a[~mask] #`~` inverts the mask index :bitwise NOT
print(result)


[1 2 3 4]


In [ ]:
# Exercise 24: Get the positions where elements of array a and b match
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 4, 3, 7, 8])

c = np.where(a == b)
print(c)

(array([0, 2]),)


In [ ]:
# Exercise 25: Extract numbers from an array
arr = np.arange(15)
print(arr[5:11])
print(arr[(arr >=5) &  (arr <= 10)])

[ 5  6  7  8  9 10]
[ 5  6  7  8  9 10]


In [20]:
# Exercise 26: Create a random 3×2 matrix and find its maximum and minimum values

array = np.random.rand(3,2)
print(f"Array: {array}")
print(f"Min: {array.min()}")
print(f"Max: {array.max()}")



Array: [[0.6820838  0.19468625]
 [0.1475929  0.17569144]
 [0.58028299 0.05635186]]
Min: 0.05635186125826275
Max: 0.6820837982696402


In [27]:
# Exercise 27: Sorting a NumPy array based on a specific column
sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])

sorted_indices = sampleArray[:, 1].argsort()

sorted_array = sampleArray[sorted_indices]

print("OG Array: ", sampleArray)
print("Sorted Array: ", sorted_array)


OG Array:  [[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorted Array:  [[82 22 12]
 [34 43 73]
 [53 94 66]]


In [30]:
# Exercise 28: Delete and Insert a Column in a NumPy Array
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumnToAdd = np.array([10, 10, 10])

# sampleArray[:, 1] = newColumnToAdd
# print(sampleArray)

deleted_column = np.delete(sampleArray, 1, axis=1)
resultArray = np.insert(deleted_column, 1, newColumnToAdd, axis=1)

print(resultArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [40]:
# Exercise 29: Swap column 1 and 2 in a 2D array

array = np.arange(9).reshape(3, 3)
# Swap_array = array[:,1]
print(f"Before\n: ", array)
array[: , [1,2]] = array[:, [2,1]]


print(f"After\n: ",array)

Before
:  [[0 1 2]
 [3 4 5]
 [6 7 8]]
After
:  [[0 2 1]
 [3 5 4]
 [6 8 7]]


In [48]:
# Exercise 30: Generate 10 random integers between 1 and 100

array = np.random.randint(100, size=(10))
print(array)

[ 2 24 10 28 19 78 73 95  6 26]


In [56]:
# Exercise 31: Create a 3×3 array of random integers and sort it row-wise
array = np.random.randint(100, size=(3,3))
print("Array:", array)
array = np.sort(array,axis= 1)
print("Array: ", array)

Array: [[30 16  6]
 [39 96 65]
 [91 71 35]]
Array:  [[ 6 16 30]
 [39 65 96]
 [35 71 91]]


In [64]:
# Exercise 32: Shuffle an array randomly
array = np.random.randint(0,100,8)
print("Array: ", array)
np.random.shuffle(array)

print("Shuffled Array: ", array)

Array:  [83 62 26 15 52 69 70  9]
Shuffled Array:  [15 83 26 62  9 70 52 69]


In [66]:
# Exercise 33: Create a 5×5 2D array with 1s on the border and 0s inside
array = np.ones((5,5))
print(array, "\n")

zero_array = np.zeros((3,3))
array[1:4, 1:4] = zero_array
# you can even make = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [75]:
# Exercise 34: Check if an array contains any NaN values.
a = np.array([1, 2, np.nan, 4, 5])

print(np.any(np.isnan(a)))

True


In [78]:
# Exercise 35: Sort the rows of a 2D array based on the values of the second column

import numpy as np
arr = np.array([[8, 4, 1],
                [5, 2, 7],
                [6, 9, 3]])
sorted_indices = arr[:, 1].argsort()
print(sorted_indices)

sorted_array = arr[sorted_indices]
print(sorted_array)

[1 0 2]
[[5 2 7]
 [8 4 1]
 [6 9 3]]


In [79]:
# Exercise 36: Flatten a multi-dimensional NumPy array

arr = np.array([[1, 2], [3, 4], [5, 6]])

print("original Array: ", arr)
print("Flattened Array: ", arr.ravel())

original Array:  [[1 2]
 [3 4]
 [5 6]]
Flattened Array:  [1 2 3 4 5 6]


In [82]:
# Exercise 37: Stack two arrays vertically and horizontally

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Vertical Stack: ", np.vstack((a,b)))
print("Horizontal Stack: ", np.hstack((a,b)))

Vertical Stack:  [[1 2 3]
 [4 5 6]]
Horizontal Stack:  [1 2 3 4 5 6]


In [85]:
# Exercise 38: Split an array into 3 equal parts

import numpy as np
arr = np.arange(9)
print(np.split(arr,3))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [88]:
# Exercise 39: Perform Addition and Squaring on Arrays

arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

print("Result of array addition: ", arrayOne + arrayTwo)

print("Result with each element squared: ", (arrayOne + arrayTwo)**2)

Result of array addition:  [[20 39 33]
 [25 25 28]]
Result with each element squared:  [[ 400 1521 1089]
 [ 625  625  784]]


In [90]:
# Exercise 40: Invert a matrix

arr = np.array([[1, 2], [3, 4]])

print(np.linalg.inv(arr))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [91]:
# Exercise 41: Use boolean indexing to filter values less than a given number

arr = np.array([5, 12, 29, 30, 44, 7, 18])
print("Values < 30 :", arr[arr< 30])

Values < 30 : [ 5 12 29  7 18]


In [97]:
# Exercise 42: Count the number of occurrences of each unique element

arr = np.array([2, 3, 2, 5, 3, 3, 2, 5])

val, counts = np.unique(arr, return_counts=True)
for v,c in zip(val, counts):
  print(f"Value {v} occurs {c} time(s)")

Value 2 occurs 3 time(s)
Value 3 occurs 3 time(s)
Value 5 occurs 2 time(s)


In [98]:
# Exercise 43: Find the intersection and union of two arrays
a = np.array([1, 2, 3, 5, 7])
b = np.array([3, 4, 5, 6, 7])

print("Intersection: ", np.intersect1d(a,b))
print("Union: ", np.union1d(a,b))

Intersection:  [3 5 7]
Union:  [1 2 3 4 5 6 7]


In [101]:
# Exercise 44: Transpose a matrix
arr = np.array([[1, 2], [3, 4]])
print(arr.T)

[[1 3]
 [2 4]]


In [103]:
# Exercise 45: Compute the eigenvalues and eigenvectors of a matrix
A = np.array([[4, 2],
              [1, 3]])
eigenvals, eigenvectors = np.linalg.eig(A)

print(f"Eigenvalues: ", eigenvals)
print(f"Eigenvectors (columns): ", eigenvectors)

Eigenvalues:  [5. 2.]
Eigenvectors (columns):  [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [106]:
# Exercise 46: Solve a linear equation
A = np.array([
    [1,2], [3,4]
])
b = np.array([8,18])

solution = np.linalg.solve(A,b)

print(solution)

[2. 3.]


In [107]:
# Exercise 47: Create an 8×8 checkerboard pattern using 0s and 1s


checkerboard = np.zeros((8,8), dtype= int)

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [109]:
# Exercise 48: Find nearest value

arr = np.array([1.5, 2.8, 3.2, 4.1])
target_value = 7

index = np.abs(arr - target_value).argmin()
nearest_value = arr[index]

print(f"The value closest to {target_value} is: {nearest_value}")

The value closest to 7 is: 4.1


In [110]:
# Exercise 49: Convert to object array

arr = np.array([1, 2, 3, 4, 5])

obj_arr = np.empty(arr.size, dtype='object')

obj_arr[:] = arr
obj_arr[1] ='a'

print(obj_arr, obj_arr.dtype)

[1 'a' 3 4 5] object


In [113]:
# Exercise 50: Compute the mean, median, and standard deviation of a NumPy array
# repeated question.

array = np.random.rand(10000)

print(f"Mean {array.mean()}, Median {np.median(array)}, STD: {array.std()}")

Mean 0.5012357789345974, Median 0.49992822069379284, STD: 0.2896673677994303
