To maintain the **structural integrity** of your development, you must follow the sequence defined in your **Battle Plan**: **Concept Attack (Study) first, then Drill Combat (Execution)**.

Here is your tactical sequence for the Day 2 NumPy mission:

### **1. The Concept Attack (60–80 Minutes)**
You should read the **NumPy Official Quickstart** before starting your loops, but do not read it passively.
*   **Focus Areas:** Prioritise understanding **ndarray shapes**, **dtypes**, and the **Broadcasting Rule**.
*   **Law 1 (Prediction):** As you encounter code examples in the documentation, you must type them manually and **predict the output** before running the cell.
*   **The Goal:** You are not just memorising syntax; you are initiating a **mental model shift** from iteration (loops) to **array thinking**.

### **2. The Drill Combat (60–80 Minutes)**
Once you have forged your initial intuition, move immediately to the **"Loop Killer"** exercises.
*   **Manual Baseline:** Write the manual Python `for` loops for the 5 scenarios (Summing 1M numbers, Row-wise means, Normalisation, etc.).
*   **Vectorised Strike:** "Kill" those loops using **vectorised NumPy operations**.
*   **Architectural Proof:** Use `%timeit` to benchmark the two versions. If you don't see a **10x to 100x speedup**, your logic has failed to bypass the Python interpreter.

### **3. The Silent Failure Mode**
While studying the docs, pay special attention to **Views vs. Copies** and **Dtype Overflow**. Your deliverable is not complete until you have **deliberately triggered a dtype overflow** (e.g., using `int32` to exceed $2^{31}$) and documented the silent wrap-around in your journal.

**Lead Architect's Command:** Do not spend the whole day reading. Your **Day 2 Deliverable** is a GitHub commit of `day2_loop_killer.ipynb` containing the 5 rewrites and timing comparisons. **The artifact is the only proof of work that counts**.

**Execute the Concept Attack now. The Lab is waiting.**

Key objectives: Understand the difference between one-, two- and n-dimensional arrays in NumPy;

Understand how to apply some linear algebra operations to n-dimensional arrays without using for-loops;

Understand axis and shape properties for n-dimensional arrays.

In [110]:
import numpy as np
import seaborn as sea
import matplotlib.pyplot as plt

In [111]:
a1 = np.array([[1., 0., 0.],
 [0., 1., 2.]])

a1.shape

(2, 3)

In [112]:
a = np.arange(15).reshape(3,5)
# 3 rows and 5 columns from 1 to 15 i was wrong it starts from 0 and goes to n-1
print(a)
print(a.shape) #(3,5)
print(a.ndim) # 2
print(a.dtype.name) #int32 wrong it is int64
print(a.itemsize) # 8 bits (not guessed)
print(a.size) # 15 as 15 elements.
print(type(a)) # ndarray of numpy



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>


In [113]:
a = np.array([1,2,3,4,5])
print(a)
b = np.arange(5)
print(b)
c = np.array([(1,2,3), (7,8,9)]) # learned a new way, using sequences of a sequences
print(c)

## Explicitly specifying the data type of the data in an array
d = np.array([[1,2,3],[4,5,6]], dtype=complex)
print(d)

# Sometimes the elements of an array are unknown but the size is known, so numpy offers several ways to create arrays with initial placeholder content. Hence minimising the necessity of growing arrays, which is an expensive operation.

[1 2 3 4 5]
[0 1 2 3 4]
[[1 2 3]
 [7 8 9]]
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [114]:
# Array that are either filled with zeros or ones or random empty values.
# Ideally used when elements are unknown but size is known.
print("Using Placeholders rather than elements when lenght is known")
a = np.zeros((3,7))
b = np.ones((3,5))
c = np.empty((4,3))
print(a, b, c, )

# To create a sequence of number: numpy offers: arange function that takes arg as (start,stop,step)

print("Using Arange")
d = np.arange(10,20,3) #start from 10 till 20-1 and step by 3
print(d)
f = np.arange(0,1,0.15) # it also accepts values as float
print(f) # when we use float it is not genrerally in our hand to predict how many numbers will be obtained.

# to fix this we use m=np.linspace(start, end, how many numbers)
from numpy import pi
print("Using Linspace")
print(np.linspace(1,8,9))
# more precise.

print(np.linspace(0, 2*pi, 100)) # 100 elements from 0-2*pi



Using Placeholders rather than elements when lenght is known
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]] [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Using Arange
[10 13 16 19]
[0.   0.15 0.3  0.45 0.6  0.75 0.9 ]
Using Linspace
[1.   1.88 2.75 3.62 4.5  5.38 6.25 7.12 8.  ]
[0.   0.06 0.13 0.19 0.25 0.32 0.38 0.44 0.51 0.57 0.63 0.7  0.76 0.83 0.89 0.95 1.02 1.08 1.14
 1.21 1.27 1.33 1.4  1.46 1.52 1.59 1.65 1.71 1.78 1.84 1.9  1.97 2.03 2.09 2.16 2.22 2.28 2.35
 2.41 2.48 2.54 2.6  2.67 2.73 2.79 2.86 2.92 2.98 3.05 3.11 3.17 3.24 3.3  3.36 3.43 3.49 3.55
 3.62 3.68 3.74 3.81 3.87 3.93 4.   4.06 4.13 4.19 4.25 4.32 4.38 4.44 4.51 4.57 4.63 4.7  4.76
 4.82 4.89 4.95 5.01 5.08 5.14 5.2  5.27 5.33 5.39 5.46 5.52 5.59 5.65 5.71 5.78 5.84 5.9  5.97
 6.03 6.09 6.16 6.22 6.28]


array, zeros, zeros_like, ones, ones_like, empty, empty_like, arange, linspace, random.Generator.random, random.Generator.normal, fromfunction, fromfile

we also have these functions

In [115]:
# while printing the arrays Numpy display it as nested lists but the following layout is used:
  # the last axis is printed from left to right, the second-tolast is printed top to bottom, and the rest are also printed from top to bottom, each slices seperated by empty line
a = np.arange(6)
print(a)

b = np.arange(12).reshape(3,4)
print(b)

c = np.arange(24).reshape(2,3,4)
print(f"{c}")

# auto skips the central part  of the arrays and only prints the corner
# print(np.arange(10000).reshape(100,100))\

np.set_printoptions(threshold=sys.maxsize)  # sys module should be imported

[0 1 2 3 4 5]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Basic operation

In [116]:
# Array arithmetic are applied elementwise.

a = np.array([20,30,40,50])
b = np.arange(4)
c = a + b
print(c)
c = a - b
print(c)
c = a*b
print(c)
# c = a/b /tmp/ipykernel_3041/4270340175.py:11: RuntimeWarning: divide by zero encountered in divide
# print(c)

print(b**2)
print(10*np.sin(b))
print(11*np.cos(a))

print(type(a<25)) ## A boolan array

[20 31 42 53]
[20 29 38 47]
[  0  30  80 150]
[0 1 4 9]
[0.   8.41 9.09 1.41]
[ 4.49  1.7  -7.34 10.61]
<class 'numpy.ndarray'>


In [117]:
# * vs @

a = np.array([[1,1],
              [9,3]])

b = np.array([[4,5],
              [8,2]])

print("The Element wise multiplication:", a * b)

print("The Matrix Multiplication:", a@b)

print("The other type of Matrix Multiplication:", np.dot(a,b))

The Element wise multiplication: [[ 4  5]
 [72  6]]
The Matrix Multiplication: [[12  7]
 [60 51]]
The other type of Matrix Multiplication: [[12  7]
 [60 51]]


In [118]:
# Operations like += or *+ modify existing array, rather than creating a new one
rg = np.random.default_rng(1)
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
a*=3
print(a)

b += a
print(b)

# a += b
# print(a)  UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'


[[3 3 3]
 [3 3 3]]
[[3.51 3.95 3.14]
 [3.95 3.31 3.42]]


In [119]:
# When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)

print(b.dtype.name)

c = a + b
print(c.dtype.name)

d = np.exp(c * 1j)
print(d)
print(d.dtype.name)

float64
float64
[ 0.54+0.84j -0.84+0.54j -0.54-0.84j]
complex128


In [120]:
# Many unary operations: such as computing the sum of all elements in the array, are implemented as method of ndarray class.

a = rg.random((2,3))
print(a)

print(a.sum())

print(a.min())

print(a.max())

print(a.cumsum())

print(a.cumprod())

# by default these operation apply to the array as though it is a list of a numbers, regradliess of the shape, However by specifying the AXIS paramter you can apply operation along the specified axis.

b = np.arange(12).reshape(3,4)
print(b)

print(b.min(axis=1))

print(b.max(axis=0))

print(b.cumsum(axis=0)) # sum along each row

[[0.83 0.41 0.55]
 [0.03 0.75 0.54]]
3.1057109529998157
0.027559113243068367
0.8277025938204418
[0.83 1.24 1.79 1.81 2.57 3.11]
[0.83 0.34 0.19 0.01 0.   0.  ]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 4 8]
[ 8  9 10 11]
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]


In [121]:
## Universal Functions

# Numpy provides mathematical functions such as sin, cos, tan, exp etc
b = np.arange(3)
print(b)

print(np.exp(b))

print(np.sqrt(b))

c = np.array([2., -1., 4.])
print(np.add(b,c))

# Other UFUNC: all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where

[0 1 2]
[1.   2.72 7.39]
[0.   1.   1.41]
[2. 0. 6.]


In [122]:
## Indexing Slicing and Iterating

# 1 D arrays can be indexed, sliced and iterated over, much like lists and other python sequences

a = np.arange(10)**3 # cube of 0-9
print(a)

print(a[2])

print(a[2:5])

print(a[:6:2])
a[:6:2]  = 1000
print(a)

# reversed a
print("Reversed Array", a[::-1])


for i in a:
  print(i**(1/3.))

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[ 0  8 64]
[1000    1 1000   27 1000  125  216  343  512  729]
Reversed Array [ 729  512  343  216  125 1000   27 1000    1 1000]
9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [123]:
## Multidimensional arrays can have one index per axis, These indices are given in a tuple seperate by commas

def f(x,y):
  return 10 * x + y

b = np.fromfunction(f, (5,4), dtype=int)
# np.fromfunction() constructs a NumPy array by executing a user-defined function over each coordinate of the specified shape.
# 0,0 1,1 etc
print(b)

print(b[2,3])

print(b[0:5, 1])

print(b[:, 1])

print(b[1:3,:]) #2nd and 3rd row all columns

# when fewer indices are provided than the number of axis the missing are considered as complete slice :

print(b[-1], "the last row equivalent to -1, :")

# The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i, ...].
# the ... represents many colons as needed to produce a complex indexing tuple.



[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]
[40 41 42 43] the last row equivalent to -1, :


In [124]:
c = np.array([[[0,1,1],
               [2,4,1]], # 1st array

              [[100,101,100], #2nd array
              [110,112,113]]])
print(c.shape)
# 2 arrays, each of 2 rows and 3 columns

print(c[1, ...])

# print(... , 2) Ellipsis 2 , Ellipsis ... is object

(2, 2, 3)
[[100 101 100]
 [110 112 113]]


In [125]:
# Iterating over mdimn array is done with respect to the first axis:
for row in b:
  print(row)

# If one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator ovwer all te elements:

for element in b.flat:
  print(element)


# Indexing on ndarrays, Indexing routines (reference), newaxis, ndenumerate, indices

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [133]:
# Shape Manipulation

# Changing the shape of an array.

# An array has a shape given by the number of elements along each axis

a = np.floor(10 * rg.random((3,4)))
print(a)

print("Shape of Array" ,a.shape)

# The shape of an array can be changed with various commands.
# These methdo return a modifed array and do not modify the og array

print("Ravel method: return a flattened array:", a.ravel())

print("Reshaped Array: note that the reshape shape must be equal to the number of elements: ", a.reshape(6,2))

print("Transposed array: the array gets flipped along its diagonal: ", a.T)
print(a.T.shape)



[[2. 0. 6. 7.]
 [8. 2. 2. 6.]
 [8. 9. 1. 4.]]
Shape of Array (3, 4)
Ravel method: return a flattened array: [2. 0. 6. 7. 8. 2. 2. 6. 8. 9. 1. 4.]
Reshaped Array: note that the reshape shape must be equal to the number of elements:  [[2. 0.]
 [6. 7.]
 [8. 2.]
 [2. 6.]
 [8. 9.]
 [1. 4.]]
Transposed array: the array gets flipped along its diagonal:  [[2. 8. 8.]
 [0. 2. 9.]
 [6. 2. 1.]
 [7. 6. 4.]]
(4, 3)


The order of the elements in the array resulting from ravel is normally “C-style”, that is, the rightmost index “changes the fastest”, so the element after a[0, 0] is a[0, 1]. If the array is reshaped to some other shape, again the array is treated as “C-style”

 The functions ravel and reshape can also be instructed, using an optional argument, to use FORTRAN-style arrays, in which the leftmost index changes the fastest.

In [139]:
# The reshape function returns its argument with a modified shape where as ndarray.resize method modifies the array itself.

print(a)
a.resize((2,6))

print(a)

# If a dimension is given as -1 in a reshaping operation, the other dimensions are auto calculated

print(a.reshape(3,-1))
print(a.reshape(4,-1))

# ndarray.shape, reshape, resize, ravel

[[2. 0. 6. 7. 8. 2.]
 [2. 6. 8. 9. 1. 4.]]
[[2. 0. 6. 7. 8. 2.]
 [2. 6. 8. 9. 1. 4.]]
[[2. 0. 6. 7.]
 [8. 2. 2. 6.]
 [8. 9. 1. 4.]]
[[2. 0. 6.]
 [7. 8. 2.]
 [2. 6. 8.]
 [9. 1. 4.]]


In [144]:
# Stacking together different arrays

a = np.floor(10 * rg.random((2,2)))
print(a)

b = np.floor(10 * rg.random((2,2)))
print(b)

print(np.vstack((a,b)))

print(np.hstack((a,b)))

[[6. 4.]
 [8. 6.]]
[[8. 3.]
 [5. 1.]]
[[6. 4.]
 [8. 6.]
 [8. 3.]
 [5. 1.]]
[[6. 4. 8. 3.]
 [8. 6. 5. 1.]]


In [147]:
# The column stack function stacks 1D array as columns into 2D array. Equivalent to hstack only for 2d arrays.

from numpy import newaxis
print(np.column_stack((a,b)))

a = np.array([[4.,2.]])
b = np.array([[3.,8.]])
print("Columns Stack of 1D arrays: ", np.column_stack((a,b)))

print("H Stack of 1D arrays: ",np.hstack((a,b)))
print("Using newaxis to see 1D vector as a 2D column vector", a[:, newaxis])

print(np.column_stack((a[:, newaxis], b[:, newaxis])))

print(np.hstack((a[:, newaxis], b[:, newaxis])))

# In general arrays with more than 2D: hstack stacks along their second axes and vstack along their first axes and concatenate allows for an optional args given the num of the axis along which concatenation mustr happen.


# Note: in Complex cases, r_ and c_ are useful for creating arrays by stacking number along one axis. They allow the use of : literal

print(np.r_[1:4, 0, 4])


[[4. 2. 3. 8.]]
Columns Stack of 1D arrays:  [[4. 2. 3. 8.]]
H Stack of 1D arrays:  [[4. 2. 3. 8.]]
Using newaxis to see 1D vector as a 2D column vector [[[4. 2.]]]
[[[4. 2.]
  [3. 8.]]]
[[[4. 2.]
  [3. 8.]]]
[1 2 3 0 4]


In [156]:
# Splitting one array into several small ones:

a = np.floor(10 * rg.random((2,12)))
print(a)

print("Splitting a into 3:", np.hsplit(a, 3))

print("Split a after 3rd and 4th column", np.hsplit(a, (3,4)))

print("Vsplit", np.vsplit(a, 2))


[[9. 6. 1. 1. 4. 0. 6. 6. 0. 8. 7. 9.]
 [6. 6. 1. 0. 0. 9. 6. 9. 3. 7. 0. 1.]]
Splitting a into 3: [array([[9., 6., 1., 1.],
       [6., 6., 1., 0.]]), array([[4., 0., 6., 6.],
       [0., 9., 6., 9.]]), array([[0., 8., 7., 9.],
       [3., 7., 0., 1.]])]
Split a after 3rd and 4th column [array([[9., 6., 1.],
       [6., 6., 1.]]), array([[1.],
       [0.]]), array([[4., 0., 6., 6., 0., 8., 7., 9.],
       [0., 9., 6., 9., 3., 7., 0., 1.]])]
Vsplit [array([[9., 6., 1., 1., 4., 0., 6., 6., 0., 8., 7., 9.]]), array([[6., 6., 1., 0., 0., 9., 6., 9., 3., 7., 0., 1.]])]


In [159]:
## COPIES and VIEWS

# When operating and manipulating arrays, their data is sometimes copied and sometimes not. This is often a source of confusion for beginners. There are three cases:


# 1. No Copies at all

a = np.array([[0, 1, 2, 3],
              [4,5,6,7],
              [8,9,10,11]])

a = b # No new bject is created as a and b point to the same object.

print(a is b)

True


In [162]:
## IN function python passes mutable object as refernces so function calls make no copy.

def f(x):
  print(id(x))

print(id(a))

f(a)

134119491544016
134119491544016


In [173]:
# 2. View or shallow copy

# the view method creates  a new array object that looks at the same data
a = np.floor(10 * rg.random((3,4)))
c = a.view()
print( c is a)
print( c== a)

print(c.flags.owndata)

print(c.base is a) # c is view of the data owned by a

print(a.shape)
c = c.reshape((2,6))
print(c.shape, a.shape)

# shape doesnt change of a when changed of c
c[0,3] = 122212
print("data changed",a)



False
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
False
True
(3, 4)
(2, 6) (3, 4)
data changed [[     8.      0.      8. 122212.]
 [     9.      6.      1.      4.]
 [     4.      6.      3.      6.]]


In [175]:
# therefore, slicing an array gives a view and not a copy. understand that changing element of a view changes the og data, but reshaping it doesnot

s = a[: 1:3]
print(s)
s[:] = 100
print(a)

[[     8.      0.      8. 122212.]]
[[100. 100. 100. 100.]
 [  9.   6.   1.   4.]
 [  4.   6.   3.   6.]]


In [176]:
## DEEP COPY
# The copy method makes a complete  copy of the array and it's data
d = a.copy()
print(d is a)
print(d.base is a, "d doesn't share anything with a")
d[00,00] = 9999
print(a, "Changing d doesnot change a")

False
False d doesn't share anything with a
[[100. 100. 100. 100.]
 [  9.   6.   1.   4.]
 [  4.   6.   3.   6.]] Changing d doesnot change a


In [179]:
# A copy should be called after slicing if the original array is not required anymore a = huge result and b is just a part of it so while creating a slice b of a a deep copy should be made.

a = np.arange(int(1e8))
b = a[:100].copy()
del a
# if b is a slice without deep copy then b will still refer to a even when a is deleted

In [180]:
# Functions and method overview.

# There are many functions: refer to numpy.org for that



In [ ]:
## Broadcasting.